# Generated by Django 3.2.3 on 2021-06-02 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('image', models.ImageField(default='images/soulful_logo.png', upload_to='industry')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'industry',
                'verbose_name_plural': 'industries',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Zipcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=20, unique=True)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=5)),
                ('county', models.CharField(default='unknown', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('state',),
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('image', models.ImageField(default='images/soulful_logo.png', upload_to='store')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='industry_stores', to='store.industry')),
                ('zipcode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zipcode_stores', to='store.zipcode')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
