# Generated by Django 3.2.3 on 2021-06-03 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_brand_product_storeproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('isActive', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'bannercategory',
                'verbose_name_plural': 'bannercategories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SocialMediaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('icon', models.ImageField(default='images/soulful_logo.png', upload_to='social_media/icon')),
                ('isActive', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'socialmediacategory',
                'verbose_name_plural': 'socialmediacategories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='StoreDetailCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('icon', models.ImageField(default='images/soulful_logo.png', upload_to='store_detail/icon')),
                ('isActive', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'store_product_sale_category',
                'verbose_name_plural': 'store_product_sale_categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='StoreProductSaleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('lable', models.CharField(blank=True, max_length=250, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'store_product_sale_category',
                'verbose_name_plural': 'store_product_sale_categories',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='store_product/images/featured_products'),
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='store_product/images/featured_products'),
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='store_product/images/featured_products'),
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='store_product/images/featured_products'),
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='image_6',
            field=models.ImageField(blank=True, null=True, upload_to='store_product/images/featured_products'),
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='image_main',
            field=models.ImageField(default='images/soulful_logo.png', upload_to='images/featured_products'),
        ),
        migrations.CreateModel(
            name='StoreProductSaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isActive', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('sale_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.storeproductsalecategory')),
                ('store_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.storeproduct')),
            ],
        ),
        migrations.CreateModel(
            name='StoreDetailItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store')),
                ('store_detail_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.storedetailcategory')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle_name', models.CharField(max_length=250)),
                ('handle_url', models.CharField(max_length=250)),
                ('isActive', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('social_media_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.socialmediacategory')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store')),
            ],
        ),
        migrations.CreateModel(
            name='FeaturedStoreProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isActive', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('store_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.storeproduct')),
            ],
        ),
        migrations.CreateModel(
            name='BannerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='images/soulful_logo.png', upload_to='banners')),
                ('isActive', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('banner_cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.bannercategory')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store')),
            ],
        ),
    ]
