# Generated by Django 3.2.3 on 2021-06-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210603_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='banneritem',
            name='name',
            field=models.CharField(default='banner_generic', max_length=250),
        ),
    ]
