# Generated by Django 3.2.3 on 2021-06-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_banneritem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediaitem',
            name='name',
            field=models.CharField(default='social_media_item_generic', max_length=250),
        ),
    ]
