# Generated by Django 3.2.3 on 2021-06-03 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_socialmediaitem_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storedetailcategory',
            options={'ordering': ('name',), 'verbose_name': 'storedetailcategory', 'verbose_name_plural': 'storedetailcategories'},
        ),
        migrations.RenameField(
            model_name='storeproductsalecategory',
            old_name='lable',
            new_name='label',
        ),
    ]
