# Generated by Django 3.2.3 on 2021-06-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210603_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storedetailcategory',
            name='icon',
        ),
        migrations.AddField(
            model_name='storedetailitem',
            name='icon',
            field=models.ImageField(default='images/soulful_logo.png', upload_to='store_detail/icon'),
        ),
    ]
