# Generated by Django 3.2.3 on 2021-06-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210603_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedetailitem',
            name='name',
            field=models.CharField(default='store_detail_generic', max_length=250),
        ),
    ]
